---
- name: Verify that required parameters are set
  ansible.builtin.assert:
    that:
      - '{{ item.key }} is defined'
      - '{{ item.key }} | length > 0'
  with_items:
    - { 'key': postgres.data_dir }
    - { 'key': postgres.db_name }
    - { 'key': guacamole.data_dir }
    - { 'key': guacamole.home }
    - { 'key': version_tags.guacd }
    - { 'key': version_tags.guacamole }
    - { 'key': version_tags.postgres }

- name: Verify that required parameters are set - bool
  ansible.builtin.assert:
    that:
      - postgres.auto_create_accounts is defined
      - postgres.auto_create_accounts | bool
...
