---
# Currently (status 20220203) there is a bug with the Dockerconatiner - version 1.4.0 of the Guacamole client
# that prevents the connection to the PostgresDB.
# The bug fix has already been integrated into CVS.
# Therefore, the container has to be built by yourself.
# source: https://issues.apache.org/jira/browse/GUACAMOLE-1433?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

# # Download container at Dockerhub
# - name: pull guacamole
#   community.docker.docker_image:
#     name: guacamole/guacamole
#     source: pull
#     tag: '{{ version_tags.guacamole }}'
#     pull:
#       platform: amd64

# Workaround: create container from source 
- name: Create temp directory
  ansible.builtin.tempfile:
    state: directory
    suffix: dockerbuild-temp
  register: dockerbuild

- name: git checkout guacamole-client
  ansible.builtin.git:
    repo: 'https://github.com/apache/guacamole-client'
    dest: '{{ dockerbuild.path }}'
    version: '{{ version_tags.guacamole }}_fix1433'

- name: build container guacamole-client aka guacamole
  community.docker.docker_image:
    name: guacamole/guacamole
    tag: 1.4.0_fix1433
    build: 
      path: '{{ dockerbuild.path }}'
    source: build
    state: present

- name: cleanup dockerbuild tempfile
  ansible.builtin.file:
    path: "{{ dockerbuild.path }}"
    state: absent

# Configure database for guacamole
- name: Create temp directory for sql-schema transfer
  ansible.builtin.tempfile:
    state: directory
    suffix: sql
  register: initdb

- name: get sql-schema
  shell: docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > '{{ initdb.path }}/initdb.sql'

- name: copy sql-schema to postgres
  shell: docker cp '{{ initdb.path }}/initdb.sql' guac-postgres:/initdb.sql

- name: populating guacamole db
  community.docker.docker_container_exec:
    container: guac-postgres
    user: '{{ vault_guacamole.postgres_user_name }}'
    command: psql guacamole_db postgres -f /initdb.sql

# cleanup workaround - build from source
- name: cleanup dockerbuild tempfile
  ansible.builtin.file:
    path: "{{ initdb.path }}"
    state: absent

# start cuacamole client
- name: create container guacamole
  community.docker.docker_container:
    name: guacamole
    image: 'guacamole/guacamole:{{ version_tags.guacamole }}_fix1433'
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: '{{ vault_guacamole.postgres_user_name }}'
      POSTGRES_PASSWORD: '{{ vault_guacamole.postgres_password }}'
      POSTGRES_DATABASE: '{{ postgres.db_name }}'
      GUACAMOLE_HOME: '{{ guacamole.home }}'
      POSTGRES_AUTO_CREATE_ACCOUNTS: '{{ postgres.auto_create_accounts }}'
    links:
      - 'guacd:guacd'
      - 'guac-postgres:postgres'
    ports:
      - 8080:8080
    volumes:
      - '{{ guacamole.data_dir }}:/guac'
...